version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: rehtman
          password: Rekhtman_12

    steps:
      - checkout

      - setup_remote_docker

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t rehtman/circleci-demo-docker:$TAG .
          docker login -u rehtman -p Rekhtman_12
          docker push rehtman/circleci-demo-docker:$TAG
