version: 2.1

jobs:
    docker:
      - image: circleci/golang:1.15
        auth:
          username: rehtman
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - setup_remote_docker:
          version: 13.03.13

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t rehtman/circleci-demo-docker:$TAG .
          docker login -u rehtman -p $DOCKERHUB_PASSWORD
          docker push rehtman/circleci-demo-docker:$TAG
